Shell homework
edgarzhavoronkov/au-software-design-fall-2016 pull request #1
Opened 2016-09-24 18:13 UTC by edgarzhavoronkov

2016-09-26 07:29 UTC, edgarzhavoronkov commented
Forgot to mention. Sorry(

2016-10-04 08:26 UTC, yurii-litvinov requested changes
В целом всё нравится, но нужно ещё больше комментариев и фиксов к мелким замечаниям по коду

2016-10-04 08:26 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/Shell.java
> +     * @param input - raw input to execute
"-" писать не надо, JavaDoc сам его сгенерирует. Как раз если написать, в сгенерённом доке будет некрасиво.

2016-10-04 08:26 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/Shell.java
> +    /**
Тут (и дальше) ещё нужно общее описание метода, то, что будет показываться с генерённой документации в списке методов класса. Иначе оно будет просто пустым.

2016-10-04 08:26 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/Shell.java
> +        tmp = Arrays.asList(tmpString.split("="));
Здесь бы ещё trim делать, а то `x = 1` не работает.

2016-10-04 08:26 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/command/Wc.java
> +                    .count();
Обычно wc реализуется так, что если у него нет параметров, он читает из входного потока, то есть `echo 123 | wc` должно работать, а не пытаться интерпретировать 123 как имя файла. То же касается cat и подобных команд. Впрочем, у нас суперпростой ненужный шелл, так что можно и как у Вас.

2016-10-04 08:26 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/util/Pair.java
> +    /**
Надо ещё сюда что-нибудь нецензурное в духе "Капитан Очевидность подсказывает, что это д-й конструктор пары" :) Ну, Java такая Java, а в дотнете есть Tuple

2016-10-04 08:26 UTC, yurii-litvinov commented on src/test/java/ru/spbau/mit/ShellTest.java
> +
Куча пустых строк подряд --- плохо.

2016-10-04 08:43 UTC, edgarzhavoronkov commented on src/main/java/ru/spbau/mit/Shell.java
> +        tmp = Arrays.asList(tmpString.split("="));
В баше тоже не работает =) (GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu))
Баш думает, что если есть пробелы, то мы команду пытаемся вызвать

2016-10-04 08:46 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/Shell.java
> +        tmp = Arrays.asList(tmpString.split("="));
Ну ладно, тогда оставьте как в баше :)

2016-10-04 09:21 UTC, edgarzhavoronkov commented
@yurii-litvinov Поправил, взгляните, пожалуйста

2016-10-04 09:59 UTC, yurii-litvinov approved these changes

2016-10-04 09:59 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/command/Command.java
> +    /**
А тут тоже надо бы комментарий

2016-10-04 09:59 UTC, merged