Cd and ls, Голованов Сергей
edgarzhavoronkov/au-software-design-fall-2016 pull request #4
Opened 2016-10-23 17:37 UTC by GolovanovSrg

@yurii-litvinov. Хорошая архитектура, все было легко.

2016-10-29 12:50 UTC, edgarzhavoronkov commented on src/main/java/ru/spbau/mit/command/Cd.java
> +        System.setProperty("user.dir", input);
@GolovanovSrg вообще неплохо бы проверить, что `input` корректный, что файл с таким именем существует и является директорией

2016-10-29 13:08 UTC, GolovanovSrg commented on src/main/java/ru/spbau/mit/command/Cd.java
> +        System.setProperty("user.dir", input);
@edgarzhavoronkov, только ради тебя, я добавил эту проверку.

2016-10-29 13:11 UTC, GolovanovSrg commented on src/main/java/ru/spbau/mit/command/Cd.java
> +        System.setProperty("user.dir", input);
Жизнь - суровая штука, нужно всегда быть на чеку и правильно выбирать директории

2016-10-29 13:23 UTC, edgarzhavoronkov commented on src/test/java/ru/spbau/mit/ShellTest.java
> +        assertEquals(newUserDirectory, System.getProperty("user.dir"));
@GolovanovSrg кажется что expected и actual попутаны местами....

2016-10-29 13:24 UTC, GolovanovSrg commented on src/test/java/ru/spbau/mit/ShellTest.java
> +        assertEquals(newUserDirectory, System.getProperty("user.dir"));
@edgarzhavoronkov, да

2016-11-03 08:02 UTC, edgarzhavoronkov commented
@GolovanovSrg 


    >> ls
    .idea
    docs
    README.md
    target
    shell-core.iml
    src
    .gitignore
    .git
    pom.xml
    >> cd ..
    ..
    >> ls
    au-software-design-fall-2016
    >> cd au-software-design-fall-2016
    Directory is not found

2016-12-06 15:12 UTC, yurii-litvinov requested changes
Доделайте, пожалуйста

2016-12-06 15:12 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/command/Cd.java
> +            return "Directory is not found";
Без is более благозвучно.

2016-12-06 15:12 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/command/Cd.java
> +public class Cd implements Command {
Нужны комментарии

2016-12-06 15:12 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/command/Ls.java
> +        return String.join("\n", files);
По идее, ls src должно показывать содержимое папки src.

2016-12-12 10:56 UTC, yurii-litvinov approved these changes

2017-01-03 11:40 UTC, merged